Repository epicmaxco/vuestic-ui, pull requests merged in 2021-08, with the labels that each got.

#913 Added language auto-detection.
  packages/docs/src/components/header/components/LanguageDropdown.vue
  packages/docs/src/locales/index.ts
Labels: docs

#966 Fix #962 Add markdown-it plugins for processing links in MarkdownView
  packages/docs/package.json
  packages/docs/src/components/DocsLink.vue
  packages/docs/src/components/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/components/page-configs/contribution/documentation-page/table-options.ts
  packages/docs/src/components/page-configs/styles/typography/page-config.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/main.ts
  packages/docs/src/markdown-it-attrs.d.ts
  packages/docs/src/utilities/markdown-view/MarkdownIt.ts
  packages/docs/src/utilities/markdown-view/MarkdownView.vue
  packages/docs/src/utilities/markdown-view/set-class-attribute-to-external-links.ts
  packages/docs/src/utilities/markdown-view/set-origin-location-to-relative-links.ts
  yarn.lock
Labels: docs, ready to merge, review required

#977 Fix #971 Fix router anchor links in docs
  packages/docs/src/components/DocsHeadline.vue
  packages/docs/src/components/DocsSubtitle.vue
  packages/docs/src/components/page-configs/contribution/documentation-page/api-options.ts
  packages/docs/src/components/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/layouts/default.vue
Labels: docs, ready to merge, review required

#987 Actions slot on card component
  packages/docs/src/components/page-configs/ui-elements/va-card/page-config.ts
  packages/docs/src/examples/va-card/Actions.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/ui/src/components/va-card/VaCard.demo.vue
  packages/ui/src/components/va-card/VaCard.vue
  packages/ui/src/components/va-card/VaCardActions.vue
  packages/ui/src/components/va-card/_variables.scss
  packages/ui/src/components/va-card/index.ts
  packages/ui/src/components/va-card/tests/VaCard.spec.disabled.ts
  packages/ui/src/components/va-card/tests/VaCardActions.spec.ts
  packages/ui/src/composables/tests/useAlign.spec.ts
  packages/ui/src/composables/useAlign.ts
  packages/ui/src/composables/useColor.ts
  packages/ui/src/shims-vue.d.ts
Labels: in progress

#954 Tree-shaking
  packages/docs/src/components/page-configs/getting-started/installation/page-config.ts
  packages/docs/src/locales/en/en.json
  packages/ui/build/config.ts
  packages/ui/build/rollup/configs/cjs.js
  packages/ui/build/rollup/configs/esm.js
  packages/ui/build/rollup/configs/iife.js
  packages/ui/build/rollup/configs/index.js
  packages/ui/build/rollup/plugins/rollup-typescript-declaration.js
  packages/ui/build/rollup/utils.js
  packages/ui/package.json
  packages/ui/rollup.config.js
  packages/ui/src/components/va-affix/VaAffix-utils.ts
  packages/ui/src/components/va-affix/VaAffix.vue
  packages/ui/src/components/va-config/VaConfig.demo.vue
  packages/ui/src/components/va-image/VaImage.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-modal/tests/VaModal.spec.disabled.ts
  packages/ui/src/data/Records.ts
  packages/ui/src/main.ts
  packages/ui/src/mixins/ClickOutsideMixin/ClickOutsideMixin.ts
  packages/ui/src/mixins/FormComponent/FormComponentMixin.ts
  packages/ui/src/services/config-transport/withConfigTransport.ts
  packages/ui/src/services/global-config/global-config.ts
  packages/ui/src/services/global-config/types.ts
  packages/ui/src/services/icon-config/icon-helpers.ts
  packages/ui/src/services/utils.ts
  packages/ui/src/vuestic-plugin/index.ts
  packages/ui/src/vuestic-plugin/vuestic-components.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin-without-components.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin.ts
  packages/ui/src/vuestic-plugin/vuestic-plugins.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: in progress

#933 Fixed clipboard button.
  packages/docs/src/components/DocsNavigation.vue
Labels: docs

#995 [WIP] Fix date input docs
  packages/docs/src/examples/va-date-input/mode.vue
  packages/docs/src/examples/va-date-input/resetOnClose.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
Labels: docs

#1013 Added styles separately to dist
  packages/ui/build/rollup/configs/cjs.js
  packages/ui/build/rollup/configs/esm.js
  packages/ui/build/rollup/configs/iife.js
  packages/ui/build/rollup/configs/index.js
  packages/ui/build/rollup/configs/styles.js
  packages/ui/build/rollup/plugins/rollup-delete-junk.js
  packages/ui/build/rollup/plugins/rollup-teaser-preset.js
  packages/ui/package.json
  packages/ui/rollup.config.js
  packages/ui/src/styles/global/global.scss
  packages/ui/src/styles/grid/_grid-spacing.scss
  packages/ui/src/styles/grid/grid-resources.scss
  packages/ui/src/styles/resources/resources.scss
  packages/ui/src/styles/vuestic-styles.scss
  yarn.lock
Labels: bug, high priority, in progress

#893 Typography re-work without using tables.
  packages/docs/src/components/DocsCode.vue
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/components/page-configs/styles/typography/page-config.ts
  packages/docs/src/examples/typography/blockquote.vue
  packages/docs/src/examples/typography/codeSnippet.vue
  packages/docs/src/examples/typography/headings.vue
  packages/docs/src/examples/typography/links.vue
  packages/docs/src/examples/typography/orderedList.vue
  packages/docs/src/examples/typography/textBlock.vue
  packages/docs/src/examples/typography/textCode.vue
  packages/docs/src/examples/typography/textHighlighted.vue
  packages/docs/src/examples/typography/textStyles.vue
  packages/docs/src/examples/typography/title.vue
  packages/docs/src/examples/typography/unorderedList.vue
  packages/docs/src/helpers/DocsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/types/configTypes.ts
Labels: docs, in progress

#1007 VA-998 move tslib to dependencies
  packages/ui/package.json
  yarn.lock
Labels: ready to merge

#1033 Add uuid generator
  packages/ui/build/rollup/configs/cjs.js
  packages/ui/build/rollup/configs/iife.js
  packages/ui/build/rollup/plugins/rollup-teaser-preset.js
  packages/ui/package.json
  packages/ui/src/components/va-option-list/VaOptionList.vue
  packages/ui/src/services/utils.spec.ts
  packages/ui/src/services/utils.ts
  yarn.lock
Labels: ready to merge

#1037 Bundlers test package
  packages/bundlers-tests/.gitignore
  packages/bundlers-tests/Readme.md
  packages/bundlers-tests/build-vuestic-ui.sh
  packages/bundlers-tests/index.html
  packages/bundlers-tests/jest.config.ts
  packages/bundlers-tests/package.json
  packages/bundlers-tests/src/App.vue
  packages/bundlers-tests/src/main.ts
  packages/bundlers-tests/src/shims-vue.d.ts
  packages/bundlers-tests/src/vite-env.d.ts
  packages/bundlers-tests/test/tree-shaking.spec.js
  packages/bundlers-tests/tsconfig.json
  packages/bundlers-tests/vite.config.ts
  packages/bundlers-tests/vue.config.js
  yarn.lock
Labels: ready to merge, review required, dependencies

#1029 Fix vite build
  packages/ui/build/rollup/configs/esm.js
  packages/ui/build/rollup/generate-rollup-inputs.js
Labels: bug, ready to merge, review required

#1047 Fix #1039 generate component script
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/scripts/generators/component/Component.vue.hbs
  packages/docs/src/scripts/generators/component/index.ts
Labels: ready to merge
