Repository epicmaxco/vuestic-ui, pull requests merged in 2021-07, with the labels that each got.

#895 Russian Translation for docs
  packages/docs/src/components/languages.ts
  packages/docs/src/components/page-configs/styles/ag-grid-wrapper/page-config.ts
  packages/docs/src/locales/ru/ru.json
Labels: in progress

#861 Fix #846 #854 #858 #868 #875 #736 Select issues, disabled state issues
  packages/docs/src/examples/va-select/Styles.vue
  packages/docs/src/locales/en/en.json
  packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/vuestic-components/va-input/VaInput.vue
  packages/ui/src/components/vuestic-components/va-select/VaSelect.demo.vue
  packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
  packages/ui/src/components/vuestic-components/va-select/VaSelectOptionList/VaSelectOptionList.vue
  packages/ui/src/components/vuestic-sass/resources/_mixins.scss
Labels: review required

#887 #862 fixed multiline button and remove unnecessary sccs variable
  packages/docs/src/utilities/markdown-view/MarkdownView.vue
  packages/ui/src/components/vuestic-components/va-badge/VaBadge.demo.vue
  packages/ui/src/components/vuestic-components/va-badge/VaBadge.vue
  packages/ui/src/components/vuestic-components/va-badge/_variables.scss
  packages/ui/src/components/vuestic-components/va-button/VaButton.demo.vue
  packages/ui/src/components/vuestic-components/va-button/VaButton.vue
Labels: docs

#970 Fix #968 Add reactive locale in links to DocsLink router-link
  packages/docs/src/components/DocsLink.vue
  packages/docs/src/components/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/components/page-configs/getting-started/configuration-guide/page-config.ts
  packages/docs/src/components/page-configs/introduction/browser-support/page-config.ts
  packages/docs/src/components/page-configs/services/colors-config/sections/api.ts
  packages/docs/src/components/page-configs/services/components-config/page-config.ts
  packages/docs/src/components/page-configs/services/global-config/page-config.ts
  packages/docs/src/components/page-configs/services/icons-config/page-config.ts
  packages/docs/src/components/page-configs/services/icons-config/sections/fonts.ts
  packages/docs/src/components/page-configs/styles/ag-grid-wrapper/page-config.ts
  packages/docs/src/components/page-configs/styles/typography/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-data-table/page-config.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
Labels: docs, ready to merge

#946 add va content break component
  packages/ui/src/components/vuestic-components/va-content/index.ts
  packages/ui/src/components/vuestic-sass/global/_typography.scss
Labels: on hold
