Repository epicmaxco/vuestic-ui, pull requests merged in 2021-06, with the labels that each got.

#828 fix: #810 #829 #830 #833 #836 sidebar items and va-collapse
  packages/docs/src/components/page-configs/ui-elements/va-collapse/page-config.ts
  packages/docs/src/components/sidebar/Sidebar.vue
  packages/ui/src/components/vuestic-components/va-accordion/VaAccordion.demo.vue
  packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue
  packages/ui/src/components/vuestic-components/va-chip/VaChip.vue
  packages/ui/src/components/vuestic-components/va-collapse/VaCollapse.demo.vue
  packages/ui/src/components/vuestic-components/va-collapse/VaCollapse.vue
  packages/ui/src/components/vuestic-components/va-list/VaListItem.vue
  packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue
  packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
  packages/ui/src/components/vuestic-components/va-switch/VaSwitch.vue
  packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue
  packages/ui/src/components/vuestic-mixins/KeyboardOnlyFocusMixin/KeyboardOnlyFocusMixin.ts
  packages/ui/src/components/vuestic-mixins/KeyboardOnlyFocusMixin/testHasKeyboardOnlyFocusMixin.ts
  packages/ui/src/components/vuestic-mixins/SelectableMixin/SelectableMixin.ts
  packages/ui/src/composables/useKeyboardOnlyFocus.ts
Labels: review required

#853 Add fonts to vue-cli-plugin
  packages/vue-cli-plugin/.eslintrc.js
  packages/vue-cli-plugin/README.md
  packages/vue-cli-plugin/generator/index.js
  packages/vue-cli-plugin/generator/template/public/index.html
Labels: review required

#863 Fix docs locale
  packages/docs/package.json
  packages/docs/src/components/header/components/LanguageDropdown.vue
  packages/docs/src/components/languages.ts
  packages/docs/src/helpers/I18nHelper.ts
  packages/docs/src/layouts/default.vue
  packages/docs/src/locales/index.ts
  packages/docs/src/main.ts
  packages/docs/src/router/index.ts
  yarn.lock
Labels: bug, docs

#856 Moved gravatar in peer dependencies.
  packages/docs/src/components/page-configs/ui-elements/va-avatar/page-config.ts
  packages/docs/src/examples/va-avatar/WithEmail.vue
  packages/docs/src/locales/en/en.json
  packages/ui/package.json
  packages/ui/src/components/vuestic-components/va-avatar/VaAvatar.demo.vue
  packages/ui/src/components/vuestic-components/va-avatar/VaAvatar.vue
Labels: in progress
