Repository epicmaxco/vuestic-ui, pull requests merged in 2021-11, with the labels that each got.

#1196 Fix#1186 Fix Va-data-table exporting, add overflow-x behavior
  packages/docs/src/examples/va-data-table/Alignment.vue
  packages/docs/src/examples/va-data-table/ColgroupSlots.vue
  packages/docs/src/examples/va-data-table/CustomSlots.vue
  packages/docs/src/examples/va-data-table/Default.vue
  packages/docs/src/examples/va-data-table/Filtering.vue
  packages/docs/src/examples/va-data-table/Other.vue
  packages/docs/src/examples/va-data-table/Pagination.vue
  packages/docs/src/examples/va-data-table/Selection.vue
  packages/docs/src/examples/va-data-table/Sorting.vue
  packages/docs/src/examples/va-data-table/StaticSlots.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/vuestic-plugin/vuestic-components.ts
Labels: bug, review required

#1170 Added prompts and treeshaking support to vue-cli
  packages/ui/package.json
  packages/vue-cli-plugin/generator/configs/default.js
  packages/vue-cli-plugin/generator/configs/index.js
  packages/vue-cli-plugin/generator/configs/treeshaking.js
  packages/vue-cli-plugin/generator/index.js
  packages/vue-cli-plugin/generator/utils/executeIfFunction.js
  packages/vue-cli-plugin/generator/utils/insertPlugin.js
  packages/vue-cli-plugin/index.js
  packages/vue-cli-plugin/package.json
  packages/vue-cli-plugin/prompts.js
Labels: bug, feature

#1213 Fix#1192 Fix VaModal, VaDropdown and VaToast z-index
  packages/docs/src/examples/va-modal/NestedModals.vue
  packages/ui/src/components/va-data-table/_variables.scss
  packages/ui/src/components/va-dropdown/_variables.scss
  packages/ui/src/components/va-modal/_variables.scss
  packages/ui/src/components/va-toast/VaToast.vue
  packages/ui/src/components/va-toast/_variables.scss
  packages/ui/src/components/va-toast/index.ts
  packages/ui/src/styles/global/css-variables.scss
Labels: bug, review required

#1181 Fix #1156 #702 Textarea resize
  packages/ui/src/components/va-checkbox/VaCheckbox.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/VaInputWrapper/VaInputWrapper.demo.vue
  packages/ui/src/components/va-input/VaInputWrapper/VaInputWrapper.vue
  packages/ui/src/components/va-input/VaInputWrapper/index.ts
  packages/ui/src/components/va-input/VaMessageList/VaMessageList.vue
  packages/ui/src/components/va-input/calculateNodeHeight.ts
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.demo.vue
  packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.vue
  packages/ui/src/components/va-input/components/VaMessageList/index.ts
  packages/ui/src/components/va-input/components/VaMessageListWrapper.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-input/components/VaTextarea/useTextareaRowHeight.ts
  packages/ui/src/components/va-input/helpers/InputMixin.ts
  packages/ui/src/components/va-input/helpers/TextareaMixin.ts
  packages/ui/src/components/va-input/hooks/useCleave.ts
  packages/ui/src/components/va-input/index.ts
  packages/ui/src/components/va-option-list/VaOptionList.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-switch/VaSwitch.vue
  packages/ui/src/composables/useBem.ts
  packages/ui/src/composables/useColor.ts
  packages/ui/src/composables/useEmitProxy.ts
  packages/ui/src/composables/useForm.ts
  packages/ui/src/vuestic-plugin/vuestic-components.ts
Labels: review required

#1225 Fix#1206 Fix VaToast examples
  packages/docs/src/examples/va-toast/Default.vue
  packages/docs/src/examples/va-toast/ExampleComponent.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/ui/src/components/va-toast/VaToast.vue
Labels: docs, review required

#1221 Fix#1203 Fix VaDataTable hooks
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/Alignment.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Pagination.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Selection.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/ui/src/components/va-card/tests/VaCardActions.spec.disabled.ts
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSelectable.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/tests/useSelectable.spec.ts
  packages/ui/src/components/va-date-input/tests/VaDateInput.spec.disabled.ts
  packages/ui/src/components/va-date-picker/tests/VaDatePicker.spec.ts
  packages/ui/src/components/va-time-input/tests/VaTimeInput.spec.disabled.ts
  packages/ui/src/components/va-time-picker/tests/VaTimePicker.spec.disabled.ts
Labels: bug

#1250 Fix#1249: Fix target selector in VaBacktop doc example
  packages/docs/src/page-configs/ui-elements/backtop/examples/Default.vue
Labels: docs, ready to merge

#1248 Fix#1243: Set tabindex for disabled VaTimePicker columns
  packages/ui/src/components/va-time-picker/VaTimePicker.vue
  packages/ui/src/components/va-time-picker/components/VaTimePickerColumn.vue
Labels: bug, review required

#1224 Fix VaAppBar docs examples
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Bottom.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Example.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Hide.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Shadow.vue
  packages/ui/src/components/va-app-bar/VaAppBar.vue
  packages/ui/src/mixins/ScrollMixin/ScrollMixin.ts
Labels: docs

#1253 Fix#1201 Fix VaCheckbox selectstart
  packages/docs/src/page-configs/ui-elements/checkbox/examples/Coloring.vue
  packages/ui/src/components/va-checkbox/VaCheckbox.vue
Labels: bug, review required

#1252 Fix#1247 Change VaChip vertical-align
  packages/docs/src/page-configs/ui-elements/chip/examples/Icon.vue
  packages/ui/src/components/va-chip/VaChip.vue
  packages/ui/src/components/va-chip/_variables.scss
Labels: review required

#1256 Fix#1171 Add flip prop to VaIcon
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/icon/examples/Rotation.vue
  packages/ui/src/components/va-icon/VaIcon.vue
Labels: feature, review required

#1272 Fix#1260 Fix VaInput id attr and algolia-search input selector
  packages/docs/src/components/sidebar/algolia-search/AlgoliaSearch.vue
  packages/ui/src/components/va-input/VaInput.vue
Labels: bug, docs

#1277 Fix #1261 Add round style to va-button-dropdown without label prop
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Default.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.demo.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
Labels: feature, review required

#1264 Fix#1204 Add VaDataTable events
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/api-options.ts
  packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Pagination.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/useSelectable.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/hooks/useStyleable.ts
Labels: feature
