Repository epicmaxco/vuestic-ui, pull requests merged in 2021-12, with the labels that each got.

#1270 Fix#1258 Fix VaSelect dropdown width
  packages/docs/src/page-configs/ui-elements/input/examples/Hint.vue
  packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
  packages/docs/src/page-configs/ui-elements/select/examples/Variations.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
  packages/ui/src/composables/useMaxSelections.ts
Labels: BUG

#1307 Fix#1281 #1302 #1291 Fix VaSelect validation
  packages/docs/src/page-configs/ui-elements/form/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Hint.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Mask.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Styles.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Textarea.vue
  packages/docs/src/page-configs/ui-elements/input/examples/Validate.vue
  packages/docs/src/page-configs/ui-elements/select/page-config.ts
  packages/ui/src/components/va-form/VaForm.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/useFormComponent.ts
  packages/ui/src/composables/useValidation.ts
Labels: BUG, EXTERNAL, groomed

#1322 Fix #1237 Add VaForm submit example
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/form/examples/Submit.vue
  packages/docs/src/page-configs/ui-elements/form/page-config.ts
  packages/ui/src/components/va-form/VaForm.demo.vue
Labels: docs

#1319 Fix#1215 #1306 Fix VaModal mobile fullscreen
  packages/docs/src/page-configs/ui-elements/modal/examples/ModalSizing.vue
  packages/ui/src/components/va-modal/VaModal.vue
Labels: BUG, EXTERNAL

#1315 Fix#1282 Add VaSelect 'create-new' emit
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/form/examples/Submit.vue
  packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
  packages/docs/src/page-configs/ui-elements/select/examples/AllowCreate.vue
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
  packages/ui/src/composables/useFormComponent.ts
Labels: FEATURE, EXTERNAL

#1349 Fix useValidation hook
  packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
  packages/docs/src/page-configs/ui-elements/sidebar-item/examples/Active.vue
  packages/docs/src/page-configs/ui-elements/sidebar-item/examples/Components.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/composables/useValidation.ts
Labels: BUG, HIGH PRIORITY

#1344 Fix behavior of select dropdown when tab key pressed
  packages/ui/src/components/va-select/VaSelect.vue
Labels: FEATURE

#1320 Fix #1226 Fix VaTimeInput bug when passed text is not valid
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-input/hooks/time-text-parser.ts
Labels: BUG, HIGH PRIORITY

#1346 Fix #1324 VaSelect dropdown position
  packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
  packages/docs/src/page-configs/ui-elements/select/examples/Slots.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
Labels: BUG, EXTERNAL

#1356 Fix#1340 Fix VaButton icon color
  packages/docs/src/page-configs/ui-elements/button/examples/WithIcon.vue
  packages/ui/src/components/va-button/VaButton.demo.vue
  packages/ui/src/components/va-button/VaButton.vue
Labels: BUG, review required, EXTERNAL

#1234 Fix #1189: Wrong version badge on npmjs
  packages/ui/README.md
Labels: ready to merge, EXTERNAL

#937 add docs page about color themes
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/es/es.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/styles/colors/examples/CustomAlert.vue
  packages/docs/src/page-configs/styles/colors/examples/DefaultColors.vue
  packages/docs/src/page-configs/styles/colors/page-config.ts
  packages/docs/src/pages/styles/colors.vue
Labels: docs, partially implemented

#1072 Add translations for code examples
  packages/docs/src/components/DocsCode.vue
  packages/docs/src/components/DocsNavigation.vue
  packages/docs/src/helpers/TranslationsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/alert/examples/Default.vue
Labels: partially implemented

#1363 VaSelect and VaCard ui bugfixes
  packages/docs/src/page-configs/ui-elements/switch/examples/Error.vue
  packages/ui/src/components/va-card/VaCard.vue
  packages/ui/src/components/va-switch/VaSwitch.vue
Labels: BUG

#1159 Tree-shaking contribution docs
  packages/docs/src/components/page-configs/contribution/tree-shaking-requirements/page-config.ts
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/es/es.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/pages/contribution/tree-shaking-requirements.vue
  packages/ui/build/rollup/plugins/rollup-delete-junk.js
Labels: DISCUSSION

#1348 Fix #1308 Fix VaInput textarea height and resize
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/input/examples/Textarea.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputField.vue
  packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.vue
  packages/ui/src/components/va-input/components/VaMessageListWrapper.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-input/components/VaTextarea/useTextareaRowHeight.ts
Labels: BUG

#1369 Fix#1347 Fix VaInfinite scroll
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Reverse.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.demo.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
  packages/ui/src/components/va-infinite-scroll/_variables.scss
  packages/ui/src/components/va-infinite-scroll/hooks/useScroll.ts
  packages/ui/src/data/Records.ts
Labels: BUG, EXTERNAL
