Repository epicmaxco/vuestic-ui, pull requests merged in 2021-09, with the labels that each got.

#1055 Fix #1053 Reworking page config files
  packages/docs/src/components/page-configs/ui-elements/va-affix/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-alert/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-avatar/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-backtop/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-badge/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-breadcrumbs/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-button/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-card/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-checkbox/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-chip/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-color-input/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-color-palette/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-date-input/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-date-picker/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-divider/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-file-upload/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-form/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-hover/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-icon/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-image/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-infinite-scroll/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-inner-loading/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-input/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-list/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-modal/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-navbar/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-option-list/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-pagination/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-parallax/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-popover/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-progress-bar/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-radio/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-rating/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-select/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/active.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/components.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/icons.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/index.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/simple.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-sidebar/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-slider/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-switch/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-tabs/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-toast/page-config.ts
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/examples/typography/codeSnippet.vue
  packages/docs/src/examples/typography/links.vue
  packages/docs/src/examples/va-toast/Close.vue
  packages/docs/src/examples/va-toast/Default.vue
  packages/docs/src/examples/va-toast/Position.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
Labels: docs, review required

#994 Add translate plugin, split i18n initialization into separate file
  packages/docs/src/App.vue
  packages/docs/src/components/DocsAlert.vue
  packages/docs/src/components/DocsApi/ApiDocs.vue
  packages/docs/src/components/DocsApi/api-docs-helpers.ts
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/components/DocsHeadline.vue
  packages/docs/src/components/DocsLink.vue
  packages/docs/src/components/DocsSubtitle.vue
  packages/docs/src/components/DocsTable/DocsTable.vue
  packages/docs/src/helpers/I18nHelper.ts
  packages/docs/src/locales/i18n.ts
  packages/docs/src/locales/translateIfExistsPlugin.ts
  packages/docs/src/main.ts
  packages/docs/src/router/index.ts
  packages/docs/src/translateIfExistsPlugin.d.ts
  packages/docs/src/utilities/markdown-view/MarkdownIt.ts
  packages/docs/src/utilities/markdown-view/MarkdownView.vue
Labels: docs

#1073 Fix #1057: Search for numbers & minor refactor
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
  packages/ui/src/composables/useSelectableList.ts
Labels: ready to merge

#1088 Fix #1054: GlobalConfig sizes, temporary solution
  package.json
  packages/ui/package.json
  packages/ui/src/components/va-icon/VaIcon.vue
  packages/ui/src/mixins/SizeMixin.ts
Labels: bug

#1103 Add translation for docs nav buttons
  packages/docs/src/components/DocsNavigation.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
Labels: partially implemented

#1084 Fix #1083. Move toggle active button styles to props.
  packages/docs/src/locales/en/en.json
  packages/ui/src/components/va-button-group/VaButtonGroup.vue
  packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
  packages/ui/src/components/va-button/_variables.scss
Labels: bug

#1097 Add conditional label for showCode btn
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
Labels: partially implemented

#1093 Show correct vuestic ui version on docs page
  packages/docs/src/components/header/components/VersionDropdown.vue
Labels: partially implemented

#1109 Fix #1042: Global & local configs
  packages/ui/src/services/config-transport/withConfigTransport.ts
Labels: bug, high priority, ready to merge

#1115 Fix #1113 Fix docs pages (services, styles)
  packages/docs/src/components/page-configs/getting-started/configuration-guide/code-examples/icons.ts
  packages/docs/src/components/page-configs/services/colors-config/code-examples/icons-config.ts
  packages/docs/src/components/page-configs/services/global-config/code-examples/reactive-set.ts
  packages/docs/src/components/page-configs/services/global-config/code-examples/reactive-update.ts
  packages/docs/src/components/page-configs/services/global-config/code-examples/setup.ts
  packages/docs/src/components/page-configs/services/icons-config/code-examples/alias-example.ts
  packages/docs/src/components/page-configs/styles/css-variables/code-examples/general.ts
Labels: docs

#1089 Fix default collapse mode-value. Fix collapse unordered animation.
  packages/ui/src/components/va-collapse/VaCollapse.vue
Labels: ready to merge

#1110 Fixed height in rounded button.
  packages/ui/src/components/va-button/VaButton.vue
Labels: ready to merge

#1111 Use cursor default in readonly input.
  packages/ui/src/components/va-input/VaInput.vue
Labels: ready to merge

#908 fixed warnings about reactive objects in docs
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/components/landing/Footer.vue
Labels: docs

#1120 Fix vuestic plugin without components.
  packages/ui/src/main.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin-without-components.ts
Labels: bug, ready to merge

#1119 Fix keyboard navigation for file upload.
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/_variables.scss
  packages/ui/src/components/va-file-upload/VaFileUploadList/VaFileUploadList.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/_variables.scss
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/_variables.scss
Labels: ready to merge

#965 Dropdown, Modal, Popover nesting
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-select/VaSelect.vue
Labels: bug, ready to merge

#1107 Added date input parse docs.
  packages/docs/src/components/DocsApi/ApiDocs.vue
  packages/docs/src/components/page-configs/ui-elements/va-date-input/code/global-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-date-input/page-config.ts
  packages/docs/src/components/page-configs/ui-elements/va-date-picker/page-config.ts
  packages/docs/src/examples/va-date-input/advancedFormatting.vue
  packages/docs/src/examples/va-date-input/input.vue
  packages/docs/src/examples/va-date-input/inputProps.vue
  packages/docs/src/examples/va-date-picker/Disabled.vue
  packages/docs/src/examples/va-date-picker/Readonly.vue
  packages/docs/src/locales/en/en.json
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-input/hooks/date-text-parser.ts
  packages/ui/src/components/va-date-picker/VaDatePicker.vue
  packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
  packages/ui/src/components/va-date-picker/components/VaDayPicker/VaDayPicker.vue
  packages/ui/src/components/va-date-picker/components/VaMonthPicker/VaMonthPicker.vue
  packages/ui/src/components/va-date-picker/components/VaYearPicker/VaYearPicker.vue
  packages/ui/src/components/va-input/VaInput.vue
Labels: ready to merge, review required

#1131 Remove console log for tabs
  packages/ui/src/components/va-tabs/VaTab/VaTab.vue
  packages/ui/src/components/va-tabs/VaTabs.vue
Labels: ready to merge

#1108 Pressed style for buttons on focus
  packages/ui/src/components/va-button/VaButton.vue
Labels: discussion
