Repository epicmaxco/vuestic-ui, pull requests merged in 2022-02, with the labels that each got.

#1474 Fix#1467 Add pagination click events to `VaTabs`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/tabs/api-options.ts
  packages/ui/src/components/va-tabs/VaTabs.vue
Labels: docs, component

#1472 Fix#1278 Fix input docs
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/input/api-options.ts
  packages/docs/src/page-configs/ui-elements/input/examples/Default.vue
  packages/ui/src/components/va-form/VaForm.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/composables/useValidation.ts
Labels: docs, component

#1383 fix VaTimeInput behavior
  packages/docs/src/page-configs/ui-elements/time-input/examples/clearable.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-picker/VaTimePicker.vue
  packages/ui/src/components/va-time-picker/components/VaTimePickerColumn.vue
  packages/ui/src/components/va-time-picker/components/_variables.scss
  packages/ui/src/components/va-time-picker/hooks/useTimePicker.ts
  packages/ui/src/composables/useFocus.ts
  packages/ui/src/styles/global/css-variables.scss
Labels: component

#1488 Fix#1471 Fix `VaSelect` and `VaInput`(`textarea`) readonly
  packages/docs/src/page-configs/ui-elements/select/examples/State.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
Labels: BUG, component

#1524 Fix/plugin without components
  packages/ui/build/rollup/generate-rollup-inputs.js
Labels: BUG

#1522 Don't use global components in vue-book. Fix unresolved components.
  packages/ui/src/components/va-button/VaButton.demo.vue
  packages/ui/src/components/va-config/VaConfig.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-date-input/VaDateInput.demo.vue
  packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
  packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-form/VaForm.demo.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-tabs/VaTabs.vue
  packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
  packages/ui/src/vue-book/book-main.ts
Labels: BUG

#1514 Fix vite SSR build
  packages/bundlers-tests/package.json
  packages/bundlers-tests/vite.config.ts
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/ui/jest.config.js
  packages/ui/package.json
  packages/ui/src/components/va-affix/VaAffix-utils.ts
  packages/ui/src/components/va-affix/VaAffix.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-icon/VaIcon.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-modal/tests/VaModal.spec.disabled.ts
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/useValidation.ts
  packages/ui/src/data/Records.ts
  packages/ui/src/mixins/ClickOutsideMixin/ClickOutsideMixin.ts
  packages/ui/src/mixins/FormComponent/FormComponentMixin.ts
  packages/ui/src/services/config-transport/withConfigTransport.ts
  packages/ui/src/services/global-config/global-config.ts
  packages/ui/src/services/icon-config/icon-helpers.ts
  packages/ui/src/services/utils.ts
  yarn.lock
Labels: BUG

#1483 Feat/vue cli plugin vite
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/installation/page-config.ts
  packages/vue-cli-plugin/README.md
  packages/vue-cli-plugin/generator/configs/default.js
  packages/vue-cli-plugin/generator/configs/index.js
  packages/vue-cli-plugin/generator/configs/treeshaking.js
  packages/vue-cli-plugin/generator/index.js
  packages/vue-cli-plugin/generator/templates/vite/index.html
  packages/vue-cli-plugin/generator/templates/vite/vite.config.ejs
  packages/vue-cli-plugin/generator/templates/vue-cli-webpack/public/index.html
  packages/vue-cli-plugin/generator/utils/getPackageJSON.js
  packages/vue-cli-plugin/generator/utils/resolveDependency.js
  packages/vue-cli-plugin/package.json
  packages/vue-cli-plugin/prompts.js
Labels: FEATURE
