Repository epicmaxco/vuestic-ui, pull requests merged in 2022-01, with the labels that each got.

#1390 VaListLabel default color
  packages/ui/src/components/va-list/VaListLabel.vue
Labels: EXTERNAL

#1405 Fix#1401 Set `display: none` to tabs slider when hideSlider=true
  packages/ui/src/components/va-tabs/VaTabs.vue
Labels: BUG, EXTERNAL

#1403 Fix#1384 Fix VaInput editing behavior
  packages/ui/src/components/va-input/hooks/useCleave.ts
Labels: BUG, EXTERNAL

#1423 Fix#1420 Correct `VaIcon` and icons config docs
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/services/icons-config/examples/font.vue
  packages/docs/src/page-configs/services/icons-config/page-config.ts
  packages/docs/src/page-configs/ui-elements/icon/examples/Default.vue
  packages/ui/src/components/va-icon/VaIcon.vue
  packages/ui/src/services/icon-config/types.ts
Labels: BUG, docs

#1421 Fix#1301 VaSelect `content` slot
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/select/api-options.ts
  packages/docs/src/page-configs/ui-elements/select/examples/ContentSlot.vue
  packages/docs/src/page-configs/ui-elements/select/page-config.ts
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-select/VaSelect.vue
Labels: BUG

#1422 Fix#1413 Add columns configuration to `VaDataTable`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/Styling.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-data-table/hooks/useStyleable.ts
Labels: FEATURE

#1412 Fix#1271 Update VaButtonDropdown
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Colors.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Events.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Icons.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Sizes.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Split.vue
  packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Styles.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.demo.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
  packages/ui/src/components/va-button-dropdown/_variables.scss
  packages/ui/src/composables/useEmitProxy.ts
  packages/ui/src/composables/useSize.ts
  packages/ui/src/composables/useStateful.ts
Labels: BUG, FEATURE

#1428 Fix#1407 Add example of `va-data-table` with CRUD
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
Labels: FEATURE, EXTERNAL

#1434 Docs fix apply translations fn
  packages/docs/src/components/DocsApi/ApiDocs.vue
  packages/docs/src/components/DocsApi/ApiTableData.ts
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/helpers/SortHelper.ts
  packages/docs/src/helpers/TranslationsHelper.ts
Labels: docs

#1394 Fix #1330 Clearable va-time-input
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/time-input/api-options.ts
  packages/docs/src/page-configs/ui-elements/time-input/examples/clearable.vue
  packages/docs/src/page-configs/ui-elements/time-input/examples/validation.vue
  packages/docs/src/page-configs/ui-elements/time-input/page-config.ts
  packages/ui/src/components/va-date-input/VaDateInput.demo.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/useClearable.ts
Labels: FEATURE
