Repository epicmaxco/vuestic-ui, pull requests merged in 2022-05, with the labels that each got.

#1679 Added code font alert in typography docs
  packages/docs/public/index.html
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/styles/typography/code-examples/font.ts
  packages/docs/src/page-configs/styles/typography/page-config.ts
Labels: docs, LOW PRIORITY

#1754 [#1751] Fix `render` and `dangerouslyUseHtmlString` props of `VaToast`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/toast/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/toast/toast-api.ts
  packages/ui/src/components/va-toast/VaToast.demo.vue
  packages/ui/src/components/va-toast/VaToast.vue
  packages/ui/src/components/va-toast/_variables.scss
  packages/ui/src/components/va-toast/types.ts
  packages/ui/src/styles/resources/_variables.scss
Labels: BUG, component

#1507 Fix#1212 VaCounter component
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/counter/api-options.ts
  packages/docs/src/page-configs/ui-elements/counter/examples/Buttons.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/ButtonsStyle.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Hint.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/IconsColors.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/MaxMinStep.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/State.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Style.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Width.vue
  packages/docs/src/page-configs/ui-elements/counter/page-config.ts
  packages/docs/src/pages/ui-elements/counter.vue
  packages/ui/src/components/va-counter/VaCounter.demo.vue
  packages/ui/src/components/va-counter/VaCounter.vue
  packages/ui/src/components/va-counter/_variables.scss
  packages/ui/src/components/va-counter/index.ts
  packages/ui/src/components/va-counter/tests/VaCounter.spec.disabled.ts
  packages/ui/src/vuestic-plugin/vuestic-components.ts
Labels: docs, component

#1766 [#1756] Fix `usePopover` `offset` prop
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-popover/VaPopover.vue
  packages/ui/src/composables/usePopover.ts
Labels: BUG, component

#1767 Fix docs bugs
  packages/docs/src/components/sidebar/algolia-search/AlgoliaSearch.vue
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/nuxt/code-examples/index.ts
  packages/docs/src/page-configs/introduction/accessibility-guide/page-config.ts
  packages/docs/src/page-configs/ui-elements/avatar/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/avatar/examples/Size.vue
  packages/docs/src/page-configs/ui-elements/button-group/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/button-group/examples/Sizes.vue
  packages/docs/src/page-configs/ui-elements/button-group/examples/Styles.vue
  packages/docs/src/page-configs/ui-elements/counter/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/hover/examples/Disabled.vue
  packages/docs/src/page-configs/ui-elements/hover/examples/Slot.vue
  packages/docs/src/page-configs/ui-elements/hover/examples/VModel.vue
  packages/docs/src/page-configs/ui-elements/image/examples/Ratio.vue
  packages/docs/src/page-configs/ui-elements/input/examples/InputClass.vue
  packages/docs/src/page-configs/ui-elements/tabs/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/tabs/examples/Pagination.vue
  packages/docs/src/pages/introduction/accessibility-guide.vue
  packages/ui/src/components/va-content/VaContent.vue
  packages/ui/src/components/va-hover/VaHover.vue
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/styles/global/css-variables.scss
  packages/ui/src/styles/global/typography.scss
Labels: BUG, docs

#1777 Fix release 1.4.0 bugs
  packages/docs/src/page-configs/ui-elements/date-input/examples/resetOnClose.vue
  packages/ui/src/components/va-date-input/VaDateInput.demo.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-input/hooks/range-model-value-guard.ts
  packages/ui/src/components/va-date-picker/VaDatePicker.vue
  packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
  packages/ui/src/components/va-date-picker/components/VaYearPicker/VaYearPicker.vue
  packages/ui/src/components/va-date-picker/hooks/use-picker.ts
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-picker/VaTimePicker.vue
Labels: BUG

#1823 Register VaHover component in VaCarousel.
  packages/ui/src/components/va-carousel/VaCarousel.vue
Labels: BUG

#1820 Updated Icon Config docs.
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/services/icons-config/examples/font.vue
  packages/docs/src/page-configs/services/icons-config/page-config.ts
Labels: docs

#1826 Fix#915/use router link in sidebar item
  packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
  packages/ui/src/composables/useHover.ts
  packages/ui/src/composables/useRouterLink.ts
Labels: BUG

#1817 Fix#1812/remove confusing config aliases
  packages/docs/src/App.vue
  packages/docs/src/components/DocsAnchor.vue
  packages/docs/src/components/header/components/ColorDropdown.vue
  packages/docs/src/components/header/components/HeaderSelector.vue
  packages/docs/src/components/header/components/LanguageDropdown.vue
  packages/docs/src/components/header/components/VuesticDocsLogo.vue
  packages/docs/src/components/header/components/VuesticLogo.vue
  packages/docs/src/components/landing/ColorTab.vue
  packages/docs/src/components/landing/Customize.vue
  packages/docs/src/components/landing/Footer.vue
  packages/docs/src/components/landing/icons/IconAdmin.vue
  packages/docs/src/components/landing/icons/IconEpicmax.vue
  packages/docs/src/components/landing/icons/IconSpinners.vue
  packages/docs/src/components/sidebar/algolia-search/algolia-color-plugin.ts
  packages/docs/src/layouts/default.vue
  packages/docs/src/page-configs/services/colors-config/code-examples/components-config.ts
  packages/docs/src/page-configs/services/colors-config/code-examples/icons-config.ts
  packages/docs/src/page-configs/services/colors-config/examples/components/colors-editor.vue
  packages/docs/src/page-configs/services/icons-config/code-examples/setup-example.ts
  packages/docs/src/page-configs/services/icons-config/examples/font.vue
  packages/docs/src/page-configs/ui-elements/hover/examples/Slot.vue
  packages/ui/src/components/va-config/VaConfig.demo.vue
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/composables/useColor.ts
  packages/ui/src/composables/useSize.ts
  packages/ui/src/main.ts
  packages/ui/src/services/color-config/ColorCSSVariablesUpdater.demo.vue
  packages/ui/src/services/color-config/color-config.ts
  packages/ui/src/services/global-config/global-config.ts
  packages/ui/src/services/icon-config/icon-config-hooks.ts
  packages/ui/src/services/icon-config/icon-helpers.ts
Labels: BUG, review required

#1832 Fix show code button focus state in docs.
  packages/docs/src/components/DocsExample.vue
Labels: docs

#1833 Prevent pagination numeric buttons changin its width if content is long.
  packages/ui/src/components/va-button-group/VaButtonGroup.vue
  packages/ui/src/components/va-button-group/_variables.scss
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/components/va-pagination/_variables.scss
Labels: BUG
