Repository epicmaxco/vuestic-ui, pull requests merged in 2022-06, with the labels that each got.

#1886 [#1885] Fix `VaTabs` `grow`
  packages/ui/src/components/va-tabs/VaTabs.vue
Labels: BUG

#1889 [#1781] Fix: docs sidebar active route determination
  packages/docs/src/components/sidebar/Sidebar.vue
Labels: docs

#1914 [#1837] Revert font size increasing
  packages/docs/src/components/DocsContent.vue
Labels: docs

#1915 [#1912] Fix `VaSlider` type `range`
  packages/ui/src/components/va-slider/VaSlider.vue
  packages/ui/src/composables/useArrayRefs.ts
Labels: BUG, component

#1894 [#1876] `VaDataTable` remove extra `click` emit
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
Labels: BUG

#1869 [#1855] `VaDataTable` customization with props `row-bind` and `cell-bind`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/api-options.ts
  packages/docs/src/page-configs/ui-elements/data-table/examples/Binding.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Styling.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/nuxt-docs/locales/en.json
  packages/nuxt-docs/locales/ru.json
  packages/nuxt-docs/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/nuxt-docs/page-configs/ui-elements/data-table/index.ts
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useBinding.ts
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/usePaginatedRows.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSelectableRow.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/hooks/useStylable.ts
  packages/ui/src/components/va-data-table/types.ts
Labels: FEATURE

#1935 Fix/component prop types
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/types.ts
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-modal/VaModal.demo.vue
  packages/ui/src/components/va-modal/VaModal.ts
  packages/ui/src/components/va-modal/index.ts
  packages/ui/src/components/va-modal/modal.ts
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/types.ts
  packages/ui/src/components/va-slider/VaSlider.demo.vue
  packages/ui/src/components/va-slider/VaSlider.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-input/hooks/time-text-formatter.ts
  packages/ui/src/composables/useArrayRefs.ts
  packages/ui/src/composables/useSelectable.ts
  packages/ui/src/composables/useSyncProp.ts
  packages/ui/src/composables/useValidation.ts
  packages/ui/src/types/prop-type.ts
  packages/ui/src/vuestic-plugin/global-components.ts
Labels: BUG

#1931 Change all vuesticPlugin to createVuestic.
  README.md
  packages/docs/src/helpers/CodeSandboxExample.ts
  packages/docs/src/helpers/CodeSandboxIconsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/colors.ts
  packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/components.ts
  packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/icons.ts
  packages/docs/src/page-configs/services/global-config/code-examples/setup.ts
  packages/docs/src/page-configs/styles/colors/code-examples/scheme.ts
  packages/docs/src/page-configs/ui-elements/date-input/code/global-config.ts
Labels: docs

#1918 [#1873] Add `VaDataTable` prop `sticky-footer`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sticky.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/nuxt-docs/locales/en.json
  packages/nuxt-docs/locales/ru.json
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/_variables.scss
  packages/ui/src/components/va-data-table/hooks/useStylable.ts
Labels: FEATURE, component

#1831 Minor. Fix Readme url.
  README.md
Labels: LOW PRIORITY

#1949 Fix VaDateInput types. Fix useBem types.
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-input/hooks/input-text-parser.ts
  packages/ui/src/components/va-date-input/hooks/model-value-parser.ts
  packages/ui/src/components/va-date-input/hooks/range-model-value-guard.ts
  packages/ui/src/components/va-date-input/types.ts
  packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
  packages/ui/src/composables/useBem.ts
  packages/ui/src/composables/useForm.ts
  packages/ui/src/composables/useParsable.ts
  packages/ui/src/composables/useStateful.ts
  yarn.lock
Labels: BUG

#1745 Remove unused emits.
  packages/docs/src/components/DocsApi/ApiDocs.vue
  packages/docs/src/components/DocsApi/ApiTableData.ts
  packages/docs/src/components/DocsApi/ManualApiOptions.ts
  packages/docs/src/components/DocsApi/api-docs-helpers.ts
  packages/docs/src/page-configs/ui-elements/accordion/api-options.ts
  packages/docs/src/page-configs/ui-elements/alert/api-options.ts
  packages/docs/src/page-configs/ui-elements/backtop/api-options.ts
  packages/docs/src/page-configs/ui-elements/button-toggle/api-options.ts
  packages/docs/src/page-configs/ui-elements/button/api-options.ts
  packages/docs/src/page-configs/ui-elements/checkbox/api-options.ts
  packages/docs/src/page-configs/ui-elements/collapse/api-options.ts
  packages/docs/src/page-configs/ui-elements/file-upload/api-options.ts
  packages/docs/src/page-configs/ui-elements/hover/api-options.ts
  packages/docs/src/page-configs/ui-elements/option-list/api-options.ts
  packages/docs/src/page-configs/ui-elements/pagination/api-options.ts
  packages/docs/src/page-configs/ui-elements/rating/api-options.ts
  packages/docs/src/page-configs/ui-elements/select/api-options.ts
  packages/docs/src/page-configs/ui-elements/slider/api-options.ts
Labels: docs

#1966 fix#1816 escape vuestic import in docs
  packages/docs/src/components/DocsCode.vue
Labels: docs

#1964 fix#1957 Remove collapse margin. Beautify accordion.
  packages/ui/src/components/va-accordion/VaAccordion.vue
  packages/ui/src/components/va-collapse/VaCollapse.vue
  packages/ui/src/components/va-collapse/_variables.scss
Labels: BUG

#1968 fix#1859 Show dropdown on manul input prop.
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
Labels: BUG

#1928 [#1752] Modal padding and Content improvements
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/ui-elements/modal/examples/CustomContent.vue
  packages/docs/src/page-configs/ui-elements/modal/page-config.ts
  packages/ui/src/components/va-modal/VaModal.demo.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-modal/_variables.scss
  packages/ui/src/styles/resources/_variables.scss
Labels: BUG, component

#1977 File upload undo examples
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/file-upload/examples/Undo.vue
  packages/docs/src/page-configs/ui-elements/file-upload/page-config.ts
Labels: docs

#1825 Docs/ssr guide
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/css-variables.ts
  packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/vite-ssr-plugin.ts
  packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/vitesse.ts
  packages/docs/src/page-configs/getting-started/ssr-guide/page-config.ts
  packages/docs/src/page-configs/ui-elements/file-upload/api-options.ts
  packages/docs/src/pages/getting-started/ssr-guide.vue
Labels: docs

#1980 Feat/popover slots rework
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/popover/api-options.ts
  packages/docs/src/page-configs/ui-elements/popover/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/popover/page-config.ts
  packages/ui/src/components/va-popover/VaPopover.demo.vue
  packages/ui/src/components/va-popover/VaPopover.vue
  packages/ui/src/components/va-popover/_variables.scss
Labels: docs, FEATURE

#1932 [#1761, #1739, #1898] Fix shallowRef and propType (part 2)
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/CustomTarget.vue
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Disabled.vue
  packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Reverse.vue
  packages/docs/src/page-configs/ui-elements/inner-loading/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/inner-loading/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/inner-loading/examples/Icon.vue
  packages/docs/src/page-configs/ui-elements/inner-loading/examples/Size.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/Colors.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/Icons.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/Sizes.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/TotalAndPageSize.vue
  packages/docs/src/page-configs/ui-elements/pagination/examples/WithInput.vue
  packages/docs/src/page-configs/ui-elements/popover/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/popover/examples/Placement.vue
  packages/docs/src/page-configs/ui-elements/popover/examples/Trigger.vue
  packages/docs/src/page-configs/ui-elements/progress-bar/examples/Buffer.vue
  packages/docs/src/page-configs/ui-elements/progress-bar/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/progress-bar/examples/Indeterminate.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.demo.vue
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
  packages/ui/src/components/va-infinite-scroll/hooks/useScroll.ts
  packages/ui/src/components/va-inner-loading/VaInnerLoading.demo.vue
  packages/ui/src/components/va-inner-loading/VaInnerLoading.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/_variables.scss
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.vue
  packages/ui/src/components/va-input/components/VaMessageListWrapper.vue
  packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
  packages/ui/src/components/va-input/hooks/useCleave.ts
  packages/ui/src/components/va-list/VaList.demo.vue
  packages/ui/src/components/va-list/index.ts
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-navbar/VaNavbar.demo.vue
  packages/ui/src/components/va-navbar/VaNavbar.vue
  packages/ui/src/components/va-navbar/index.ts
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/components/va-parallax/VaParallax.vue
  packages/ui/src/components/va-popover/VaPopover.vue
  packages/ui/src/components/va-popover/_variables.scss
  packages/ui/src/components/va-progress-bar/VaProgressBar.demo.vue
  packages/ui/src/components/va-progress-bar/VaProgressBar.vue
  packages/ui/src/components/va-progress-bar/_variables.scss
  packages/ui/src/services/testHasColorThemeMixin.ts
  packages/ui/src/services/utils.ts
Labels: refactoring

#1984 Fix: va-rating-issues
  packages/ui/src/components/va-rating/VaRating.demo.vue
  packages/ui/src/components/va-rating/VaRating.vue
  packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
  packages/ui/src/components/va-rating/hooks/useRating.ts
Labels: BUG

#1990 [#1940] Fixed filtering and sorting of `VaDataTable` when using `items` with nested objects
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/CustomSlots.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Selection.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/types.ts
Labels: BUG

#1981 Fix incorrectly applied progress bar height (#1950)
  packages/ui/src/components/va-progress-bar/VaProgressBar.vue
Labels: BUG

#2007 hotfix/var-date
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Hide.vue
  packages/ui/src/components/va-app-bar/VaAppBar.vue
  packages/ui/src/components/va-app-bar/_variables.scss
  packages/ui/tsconfig.json
  tsconfig.json
Labels: BUG

#2027 [#1985] Fix `VaProgressBar` slot position
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/progress-bar/examples/Slots.vue
  packages/ui/src/components/va-progress-bar/VaProgressBar.demo.vue
  packages/ui/src/components/va-progress-bar/VaProgressBar.vue
  packages/ui/src/components/va-progress-bar/_variables.scss
Labels: FEATURE
