Repository epicmaxco/vuestic-ui, pull requests merged in 2022-03, with the labels that each got.

#1432 Feat/carousel
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/carousel/api-options.ts
  packages/docs/src/page-configs/ui-elements/carousel/examples/Arrows.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Autoscroll.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Fade.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Indicators.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Infinite.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/carousel/examples/Vertical.vue
  packages/docs/src/page-configs/ui-elements/carousel/page-config.ts
  packages/docs/src/pages/ui-elements/carousel.vue
  packages/ui/src/components/va-carousel/VaCarousel.demo.vue
  packages/ui/src/components/va-carousel/VaCarousel.vue
  packages/ui/src/components/va-carousel/_variables.scss
  packages/ui/src/components/va-carousel/hooks/useCarousel.ts
  packages/ui/src/components/va-carousel/hooks/useCarouselAnimation.ts
  packages/ui/src/components/va-carousel/hooks/useCarouselColors.ts
  packages/ui/src/components/va-carousel/index.ts
  packages/ui/src/components/va-carousel/tests/VaCarousel.spec.ts
  packages/ui/src/components/va-hover/VaHover.vue
  packages/ui/src/vuestic-plugin/vuestic-components.ts
Labels: component

#1501 Feat nuxt3
  packages/ui/build/rollup/configs/esm.js
  packages/ui/package.json
  packages/ui/src/components/va-collapse/VaCollapse.vue
  packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-dropdown/components/VaDropdownContent/VaDropdownContent.vue
  packages/ui/src/components/va-dropdown/components/VaDropdownContent/_variables.scss
  packages/ui/src/components/va-dropdown/components/VaDropdownContent/index.ts
  packages/ui/src/components/va-dropdown/index.ts
  packages/ui/src/components/va-dropdown/plugin/index.ts
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/components/va-popover/VaPopover.vue
  packages/ui/src/components/va-slider/VaSlider.vue
  packages/ui/src/components/va-tabs/VaTabs.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-toast/plugin/index.ts
  packages/ui/src/composables/useClickOutside.ts
  packages/ui/src/composables/useDebounce.ts
  packages/ui/src/composables/useDomRect.ts
  packages/ui/src/composables/useHover.ts
  packages/ui/src/composables/usePopover.ts
  packages/ui/src/services/color-config/plugin/index.ts
  packages/ui/src/services/global-config/plugin/index.ts
  packages/ui/src/utils/map-object.ts
  packages/ui/src/vue-book/book-main.ts
  packages/ui/src/vuestic-plugin/index.ts
  packages/ui/src/vuestic-plugin/vuestic-nuxt-plugin.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin-without-components.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin.ts
  packages/ui/src/vuestic-plugin/vuestic-plugins.ts
  yarn.lock
Labels: FEATURE

#1464 Feat/toast composition hook
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/ui-elements/toast/examples/composition-api.ts
  packages/docs/src/page-configs/ui-elements/toast/examples/options-api.ts
  packages/docs/src/page-configs/ui-elements/toast/page-config.ts
  packages/docs/src/page-configs/ui-elements/toast/toast-api.ts
  packages/ui/src/components/va-toast/VaToast.demo.vue
  packages/ui/src/components/va-toast/plugin/index.ts
  packages/ui/src/components/va-toast/toast.ts
  packages/ui/src/components/va-toast/types.ts
  packages/ui/src/components/va-toast/useToast.ts
Labels: docs, FEATURE, DISCUSSION

#1538 Refactor/hover image icon
  packages/ui/src/components/va-hover/VaHover.vue
  packages/ui/src/components/va-icon/VaIcon.vue
  packages/ui/src/components/va-image/VaImage.vue
Labels: refactoring

#1541 Add option grouping to select component
  packages/docs/src/locales/en/en.json
  packages/ui/src/components/va-option-list/VaOptionList.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
  packages/ui/src/components/va-select/VaSelectOptionList/_variables.scss
  packages/ui/src/composables/useSelectableList.ts
Labels: FEATURE, refactoring

#1515 Feat/required mark
  packages/docs/src/locales/en/en.json
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
Labels: FEATURE

#1506 Refactor/file upload
  packages/ui/src/components/va-divider/DividerWithList.vue
  packages/ui/src/components/va-divider/VaDivider.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadList/VaFileUploadList.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue
  packages/ui/src/components/va-file-upload/_variables.scss
  packages/ui/src/components/va-file-upload/types.ts
Labels: refactoring

#1502 Added folders to component folder structure.
  packages/docs/src/page-configs/contribution/guide/code-examples/folder-structure.ts
Labels: docs, DISCUSSION

#1531 Fix#1529 Add `VaDateInput` validation
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/date-input/examples/inputProps.vue
  packages/docs/src/page-configs/ui-elements/date-input/examples/validation.vue
  packages/docs/src/page-configs/ui-elements/date-input/page-config.ts
  packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
  packages/ui/src/components/va-date-input/VaDateInput.demo.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-input/hooks/range-model-value-guard.ts
  packages/ui/src/components/va-date-picker/VaDatePicker.vue
  packages/ui/src/components/va-form/VaForm.demo.vue
Labels: BUG, component

#1523 Fix#1493 Fix `VaDataTable` selection behavior, add `sticky-header`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Pagination.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/StickyHeader.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/ui/src/components/va-data-table/VaDataTable.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/_variables.scss
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/usePaginatedRows.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSelectableRow.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/hooks/useStyleable.ts
  packages/ui/src/components/va-data-table/tests/useSelectableRow.spec.disabled.ts
  packages/ui/src/components/va-data-table/types/index.ts
  packages/ui/src/styles/resources/_mixins.scss
  packages/ui/src/utils/css-utils.ts
Labels: BUG, docs, component
