Repository epicmaxco/vuestic-ui, pull requests merged in 2022-07, with the labels that each got.

#2036 [#2033] Fix `VaDropdown` font
  packages/ui/src/components/va-dropdown/VaDropdown.vue
Labels: BUG

#2011 Feat/input counter and max length
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/input/examples/Default.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/_variables.scss
  packages/ui/src/components/va-input/components/VaInputWrapper.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
Labels: FEATURE

#2058 [#2038] Add visuals to active cell on focus in `va-time-picker`
  packages/ui/src/components/va-time-picker/components/VaTimePickerColumn/VaTimePickerColumn.vue
  packages/ui/src/styles/resources/_mixins.scss
Labels: BUG

#2065 Improve CSS Variables docs page.
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/styles/css-variables/code-examples/component.ts
  packages/docs/src/page-configs/styles/css-variables/code-examples/general.ts
  packages/docs/src/page-configs/styles/css-variables/code-examples/index.ts
  packages/docs/src/page-configs/styles/css-variables/code-examples/overriding.ts
  packages/docs/src/page-configs/styles/css-variables/components/convention.vue
  packages/docs/src/page-configs/styles/css-variables/components/global-overriding.vue
  packages/docs/src/page-configs/styles/css-variables/examples/profile.vue
  packages/docs/src/page-configs/styles/css-variables/page-config.ts
  packages/docs/src/types/configTypes.ts
  packages/ui/src/styles/grid/_grid-global-styles.scss
Labels: docs

#2096 Fix sidebar text color.
  packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
Labels: BUG

#2089 Docs/icon config examples
  packages/docs/.stylelintrc.js
  packages/docs/src/components/demo/CodeInput.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/services/icons-config/code-examples/alias-example.ts
  packages/docs/src/page-configs/services/icons-config/code-examples/font-example.ts
  packages/docs/src/page-configs/services/icons-config/code-examples/index.ts
  packages/docs/src/page-configs/services/icons-config/components/examples.ts
  packages/docs/src/page-configs/services/icons-config/components/playground-utils.ts
  packages/docs/src/page-configs/services/icons-config/components/playground.vue
  packages/docs/src/page-configs/services/icons-config/components/use-copy-to-clipboard.ts
  packages/docs/src/page-configs/services/icons-config/components/use-example-select.ts
  packages/docs/src/page-configs/services/icons-config/examples/font.vue
  packages/docs/src/page-configs/services/icons-config/page-config.ts
  packages/docs/src/page-configs/ui-elements/icon/page-config.ts
  packages/nuxt-docs/locales/en.json
  packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
  packages/ui/src/components/va-input/components/VaInputWrapper/_variables.scss
Labels: docs, ready to merge, review needed

#2101 Fix multiple select value-by prop & nuxt version bump...
  packages/nuxt/package.json
  packages/ui/src/components/va-select/VaSelect.vue
Labels: BUG

#2105 Css code split docs and essentail css in build
  packages/docs/src/assets/main.scss
  packages/docs/src/components/header/components/algolia-search/AlgoliaSearch.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/getting-started/installation/code-examples/quick-start.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/code-examples/css-code-split.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/code-examples/tree-shaking.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/page-config.ts
  packages/ui/build/vite/build.mjs
  packages/ui/build/vite/configs/vite.styles-essential.js
  packages/ui/src/styles/index.scss
Labels: BUG, docs

#2110 [#2067] Add `animated` prop to `VaSidebar`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/ui/src/components/va-sidebar/VaSidebar.vue
Labels: FEATURE

#2097 Feat/file upload rework
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/file-upload/examples/Undo.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadList/VaFileUploadList.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/_variables.scss
  packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/_variables.scss
  packages/ui/src/components/va-file-upload/types.ts
  packages/ui/src/components/va-list/VaListItem.vue
  packages/ui/src/components/va-list/_variables.scss
Labels: FEATURE, refactoring

#2064 docs/typography
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/components/DocsHeadline.vue
  packages/docs/src/components/DocsNavigation.vue
  packages/docs/src/components/DocsSubtitle.vue
  packages/docs/src/components/header/components/algolia-search/AlgoliaSearch.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/styles/typography/examples/headings.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading1.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading2.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading3.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading4.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading5.vue
  packages/docs/src/page-configs/styles/typography/examples/headings/heading6.vue
  packages/docs/src/page-configs/styles/typography/examples/text-helpers/alignment.vue
  packages/docs/src/page-configs/styles/typography/examples/text-helpers/transform.vue
  packages/docs/src/page-configs/styles/typography/examples/text-helpers/truncate.vue
  packages/docs/src/page-configs/styles/typography/examples/text/default.vue
  packages/docs/src/page-configs/styles/typography/examples/text/secondary.vue
  packages/docs/src/page-configs/styles/typography/examples/textHighlighted.vue
  packages/docs/src/page-configs/styles/typography/examples/textStyles.vue
  packages/docs/src/page-configs/styles/typography/page-config.ts
  packages/ui/src/components/va-content/VaContent.vue
  packages/ui/src/components/va-icon/VaIcon.vue
  packages/ui/src/styles/global/_utility-global.scss
  packages/ui/src/styles/global/reset.scss
  packages/ui/src/styles/global/typography.scss
  packages/ui/src/styles/grid/_grid-global-styles.scss
  packages/ui/src/styles/resources/_mixins.scss
  packages/ui/src/styles/resources/_variables.scss
Labels: docs

#2109 docs: dropdown
  packages/docs/package.json
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/config/vuestic-config.ts
  packages/docs/src/layouts/default.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/date-input/examples/inputProps.vue
  packages/docs/src/page-configs/ui-elements/dropdown/api-options.ts
  packages/docs/src/page-configs/ui-elements/dropdown/components/Coordinates.vue
  packages/docs/src/page-configs/ui-elements/dropdown/examples/Cursor.vue
  packages/docs/src/page-configs/ui-elements/dropdown/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/dropdown/examples/PlacementAndOffset.vue
  packages/docs/src/page-configs/ui-elements/dropdown/examples/PreventOverflow.vue
  packages/docs/src/page-configs/ui-elements/dropdown/examples/Trigger.vue
  packages/docs/src/page-configs/ui-elements/dropdown/page-config.ts
  packages/docs/src/pages/ui-elements/dropdown.vue
  packages/docs/tsconfig.json
  packages/ui/src/components/va-counter/VaCounter.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-dropdown/_variables.scss
  packages/ui/src/components/va-dropdown/hooks/useAnchorSelector.ts
  packages/ui/src/components/va-dropdown/hooks/useCursorAnchor.ts
  packages/ui/src/components/va-dropdown/tests/VaDropdown.spec.ts
  packages/ui/src/components/va-input/components/VaInputWrapper/_variables.scss
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/index.ts
  packages/ui/src/composables/useDocument.ts
  packages/ui/src/composables/useEvent.ts
  packages/ui/src/composables/useIsMounted.ts
  packages/ui/src/composables/useMousePosition.ts
  packages/ui/src/composables/usePopover.ts
  packages/ui/src/composables/useWindow.ts
  yarn.lock
Labels: BUG, docs, key feature

#2143 fix(ssr): modal window is undefined
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/composables/useWindow.ts
Labels: BUG

#2137 Feat/nuxt treeshaking
  packages/deploy/execute/defineExecute.ts
  packages/deploy/execute/index.ts
  packages/deploy/package.json
  packages/nuxt/package.json
  packages/nuxt/src/composables/use-components.ts
  packages/nuxt/src/composables/use-composables.ts
  packages/nuxt/src/composables/use-css.ts
  packages/nuxt/src/composables/use-plugin.ts
  packages/nuxt/src/config/components.ts
  packages/nuxt/src/config/composables.ts
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/plugin.ts
  packages/nuxt/src/types.ts
  packages/ui/build/vite/build.ts
  packages/ui/build/vite/utils.mjs
  packages/ui/package.json
  yarn.lock
Labels: FEATURE, nuxt

#2144 nuxt/tree-shaking-docs
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/getting-started/nuxt/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/nuxt/page-config.ts
  packages/nuxt/src/composables/use-components.ts
  packages/nuxt/src/composables/use-css.ts
  packages/nuxt/src/composables/use-transpile.ts
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/plugin.ts
  packages/nuxt/src/types.ts
  packages/ui/build/vite/build.ts
  packages/ui/build/vite/common-config.js
  packages/ui/build/vite/configs/vite.esm.js
  packages/ui/build/vite/configs/vite.styles.js
  packages/ui/build/vite/define-vuestic-build.ts
  packages/ui/build/vite/plugins/append-component-css.js
  packages/ui/build/vite/steps/cleanJunk.ts
  packages/ui/build/vite/steps/removeDist.ts
  packages/ui/build/vite/utils.mjs
Labels: BUG, docs, nuxt

#2134 [#2122] Accessibility guide
  packages/ui/src/components/AccessibilityGuide.md
Labels: accessibility

#2165 [#2163] Fix `VaInputWrapper` `min-width`
  packages/ui/src/components/va-counter/VaCounter.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-input/_variables.scss
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
  packages/ui/src/components/va-input/components/VaInputWrapper/_variables.scss
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/_variables.scss
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-input/_variables.scss
  packages/ui/src/styles/global/css-variables.scss
Labels: BUG, component

#2161 fix: files list items disabled state
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/file-upload/examples/Disabled.vue
  packages/docs/src/page-configs/ui-elements/file-upload/page-config.ts
  packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadList/VaFileUploadList.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue
  packages/ui/src/components/va-file-upload/types.ts
  packages/ui/src/components/va-list/VaListItem.vue
  packages/ui/src/composables/index.ts
  packages/ui/src/composables/useStrictInject.ts
Labels: BUG, EXTERNAL

#2159 fix(collapse): collapse content must change height if it content is height is changed
  packages/ui/src/components/va-collapse/VaCollapse.demo.vue
  packages/ui/src/components/va-collapse/VaCollapse.vue
Labels: BUG

#2162 Refactroing/cleaning
  packages/README.md
  packages/docs/src/assets/data/Users.ts
  packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.demo.vue
  packages/ui/src/components/va-infinite-scroll/demo/Records.ts
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/demo/CountriesList.ts
  packages/ui/src/types/v-tooltip.d.ts
  packages/vue-cli-example/.browserslistrc
  packages/vue-cli-example/.editorconfig
  packages/vue-cli-example/.eslintrc.js
  packages/vue-cli-example/.gitignore
  packages/vue-cli-example/README.md
  packages/vue-cli-example/babel.config.js
  packages/vue-cli-example/package.json
  packages/vue-cli-example/public/favicon.ico
  packages/vue-cli-example/public/index.html
  packages/vue-cli-example/src/App.vue
  packages/vue-cli-example/src/assets/logo.png
  packages/vue-cli-example/src/components/HelloWorld.vue
  packages/vue-cli-example/src/main.js
  packages/vue-cli-example/src/router/index.js
  packages/vue-cli-example/src/views/About.vue
  packages/vue-cli-example/src/views/Home.vue
  packages/vue-cli-example/vue.config.js
  tsconfig.json
Labels: discussion

#2147 docs/roadmap-1-5-0
  packages/docs/src/components/DocsComponent.vue
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/helpers/DocsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/introduction/roadmap/components/roadmap.vue
  packages/docs/src/page-configs/introduction/roadmap/images/attributes-config.vue
  packages/docs/src/page-configs/introduction/roadmap/images/breakpoints.vue
  packages/docs/src/page-configs/introduction/roadmap/images/buttons.vue
  packages/docs/src/page-configs/introduction/roadmap/images/css-helpers.vue
  packages/docs/src/page-configs/introduction/roadmap/images/dark-theme.vue
  packages/docs/src/page-configs/introduction/roadmap/images/dropdown.vue
  packages/docs/src/page-configs/introduction/roadmap/images/index.ts
  packages/docs/src/page-configs/introduction/roadmap/images/presets.vue
  packages/docs/src/page-configs/introduction/roadmap/images/skeleton.vue
  packages/docs/src/page-configs/introduction/roadmap/images/split-panel.vue
  packages/docs/src/page-configs/introduction/roadmap/images/tree-view.vue
  packages/docs/src/page-configs/introduction/roadmap/page-config.ts
  packages/docs/src/page-configs/introduction/roadmap/types.ts
  packages/docs/src/types/configTypes.ts
Labels: docs, discussion

#2154 feat(dropdown): prevent-overflow prop.
  packages/docs/src/components/DocsExample.vue
  packages/docs/src/layouts/default.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/ui-elements/dropdown/examples/PreventOverflow.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-picker/hooks/grid-keyboard-navigation.ts
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-dropdown/hooks/useAnchorSelector.ts
  packages/ui/src/components/va-dropdown/hooks/useCursorAnchor.ts
  packages/ui/src/components/va-dropdown/hooks/useDropdownNavigation.ts
  packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/index.ts
  packages/ui/src/composables/useDropdown.ts
  packages/ui/src/composables/useEvent.ts
  packages/ui/src/composables/useFocusDeep.ts
  packages/ui/src/composables/useHTMLElement.ts
Labels: FEATURE, optimization

#2167 [#2119] Update `VaDataTable` sorting with `sortingOptions` prop
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/api-options.ts
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useAnimationName.ts
  packages/ui/src/components/va-data-table/hooks/useBinding.ts
  packages/ui/src/components/va-data-table/hooks/useColumns.ts
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/usePaginatedRows.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSelectableRow.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/hooks/useStylable.ts
  packages/ui/src/components/va-data-table/types.ts
Labels: FEATURE

#2177 Fix `VaInput` and `VaSelect` wrapper class
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-select/VaSelect.vue
Labels: BUG

#2180 Fix `VaListItemLabel` `line-height`
  packages/ui/src/components/va-list/VaListItemLabel.vue
  packages/ui/src/components/va-list/_variables.scss
Labels: BUG
