Repository epicmaxco/vuestic-ui, pull requests merged in 2022-10, with the labels that each got.

#2453 Fix `VaDataTable` filtering animation
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useAnimationName.ts
Labels: BUG, component

#2389 [#2295] `VaDataTable` scroll events
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/api-options.ts
  packages/docs/src/page-configs/ui-elements/data-table/examples/Binding.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/ColgroupSlots.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Pagination.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/StaticSlots.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Sticky.vue
  packages/docs/src/page-configs/ui-elements/data-table/examples/Styling.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/_variables.scss
  packages/ui/src/components/va-data-table/hooks/useStylable.ts
  packages/ui/src/components/va-data-table/hooks/useTableScroll.ts
  packages/ui/src/composables/index.ts
  packages/ui/src/composables/useIntersectionObserver.ts
Labels: FEATURE

#2438 feat: added threshold to colors config
  packages/docs/src/App.vue
  packages/docs/src/components/header/components/ColorDropdown.vue
  packages/docs/src/components/header/components/algolia-search/AlgoliaSearch.vue
  packages/docs/src/components/landing/LandingColorTab.vue
  packages/docs/src/components/landing/LandingCustomize.vue
  packages/docs/src/config/theme-config.ts
  packages/docs/src/page-configs/services/colors-config/examples/change-colors.vue
  packages/docs/src/page-configs/services/colors-config/examples/css-variable.vue
  packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
  packages/ui/src/composables/useColors.ts
  packages/ui/src/main.ts
  packages/ui/src/services/color-config/color-functions.ts
  packages/ui/src/services/color-config/color-theme-presets.ts
  packages/ui/src/services/color-config/composables/useTheme.ts
  packages/ui/src/services/color-config/index.ts
  packages/ui/src/services/color-config/plugin/create-color-config-plugin.ts
  packages/ui/src/services/color-config/types.ts
  packages/ui/src/services/global-config/global-config.ts
Labels: discussion

#2473 fix#1936: va icon aliases
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/services/icons-config/components/icon-aliases.vue
  packages/docs/src/page-configs/services/icons-config/page-config.ts
  packages/ui/src/components/va-backtop/VaBacktop.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
  packages/ui/src/components/va-carousel/VaCarousel.vue
  packages/ui/src/components/va-checkbox/VaCheckbox.vue
  packages/ui/src/components/va-checkbox/tests/VaCheckbox.spec.disabled.ts
  packages/ui/src/components/va-chip/VaChip.vue
  packages/ui/src/components/va-collapse/VaCollapse.vue
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
  packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-select/components/VaSelectOption/VaSelectOption.vue
  packages/ui/src/components/va-select/demo/DemoData.ts
  packages/ui/src/components/va-tabs/VaTabs.vue
  packages/ui/src/composables/useClearable.ts
  packages/ui/src/services/icon-config/presets/fonts.ts
  packages/ui/src/services/icon-config/presets/vuestic-aliases.ts
Labels: breaking changes

#2481 fix: two index in styles build
  packages/ui/src/styles/essential.scss
  packages/ui/src/styles/global/index.scss
  packages/ui/src/styles/global/theme.scss
  packages/ui/src/styles/grid/_grid-global-styles.scss
  packages/ui/src/styles/grid/_grid-variables.scss
  packages/ui/src/styles/index.scss
Labels: BUG, build

#2524 fix: css variables names
  packages/ui/src/components/va-alert/_variables.scss
  packages/ui/src/components/va-backtop/_variables.scss
  packages/ui/src/components/va-checkbox/VaCheckbox.vue
  packages/ui/src/components/va-checkbox/_variables.scss
  packages/ui/src/components/va-chip/VaChip.vue
  packages/ui/src/components/va-chip/_variables.scss
  packages/ui/src/components/va-counter/VaCounter.vue
  packages/ui/src/components/va-counter/_variables.scss
  packages/ui/src/components/va-data-table/_variables.scss
  packages/ui/src/components/va-date-picker/_variables.scss
  packages/ui/src/components/va-divider/VaDivider.vue
  packages/ui/src/components/va-divider/_variables.scss
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/_variables.scss
  packages/ui/src/components/va-parallax/VaParallax.vue
  packages/ui/src/components/va-parallax/_variables.scss
  packages/ui/src/components/va-popover/_variables.scss
  packages/ui/src/components/va-progress-bar/VaProgressBar.vue
  packages/ui/src/components/va-progress-bar/_variables.scss
  packages/ui/src/components/va-progress-circle/VaProgressCircle.vue
  packages/ui/src/components/va-progress-circle/_variables.scss
  packages/ui/src/components/va-radio/VaRadio.vue
  packages/ui/src/components/va-radio/_variables.scss
  packages/ui/src/components/va-rating/VaRating.vue
  packages/ui/src/components/va-rating/_variables.scss
  packages/ui/src/components/va-sidebar/_variables.scss
  packages/ui/src/components/va-slider/VaSlider.vue
  packages/ui/src/components/va-slider/_variables.scss
  packages/ui/src/components/va-switch/VaSwitch.vue
  packages/ui/src/components/va-switch/_variables.scss
  packages/ui/src/components/va-tabs/VaTabs.vue
  packages/ui/src/components/va-tabs/_variables.scss
  packages/ui/src/components/va-toast/VaToast.vue
  packages/ui/src/components/va-toast/_variables.scss
Labels: breaking changes

#2499 Feat/nuxt fixes
  packages/docs/src/components/sidebar/Sidebar.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/accordion/examples/Multiply.vue
  packages/docs/src/page-configs/ui-elements/accordion/page-config.ts
  packages/docs/src/page-configs/ui-elements/sidebar-item/examples/Components.vue
  packages/ui/src/components/va-accordion/VaAccordion.demo.vue
  packages/ui/src/components/va-accordion/VaAccordion.vue
  packages/ui/src/components/va-accordion/hooks/useAccordion.ts
  packages/ui/src/components/va-backtop/VaBacktop.vue
  packages/ui/src/components/va-date-picker/components/VaDayPicker/VaDayPicker.vue
  packages/ui/src/components/va-date-picker/components/VaMonthPicker/VaMonthPicker.vue
  packages/ui/src/components/va-date-picker/components/VaYearPicker/VaYearPicker.vue
  packages/ui/src/components/va-modal/VaModal.demo.vue
  packages/ui/src/services/dom-functions.ts
Labels: breaking changes

#2443 chore: update contribution guide documentation
  packages/docs/src/components/DocsLink.vue
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/contribution/documentation-page/code-examples/structure.ts
  packages/docs/src/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/page-configs/contribution/guide/code-examples/index.ts
  packages/docs/src/page-configs/contribution/guide/code-examples/npm-scripts.ts
  packages/docs/src/page-configs/contribution/guide/page-config.ts
  packages/docs/src/types/configTypes.ts
Labels: docs

#2471 Feat/i18n
  packages/ui/src/components/va-alert/VaAlert.vue
  packages/ui/src/components/va-backtop/VaBacktop.vue
  packages/ui/src/components/va-breadcrumbs/VaBreadcrumbs.vue
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
  packages/ui/src/components/va-carousel/VaCarousel.vue
  packages/ui/src/components/va-chip/VaChip.vue
  packages/ui/src/components/va-color-input/VaColorInput.vue
  packages/ui/src/components/va-color-palette/VaColorPalette.vue
  packages/ui/src/components/va-counter/VaCounter.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-dropdown/tests/VaDropdown.spec.disabled.ts
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
  packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/components/va-navbar/VaNavbar.vue
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/components/va-progress-bar/VaProgressBar.vue
  packages/ui/src/components/va-progress-circle/VaProgressCircle.vue
  packages/ui/src/components/va-rating/VaRating.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-split/VaSplit.vue
  packages/ui/src/components/va-tabs/VaTabs.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-toast/VaToast.vue
  packages/ui/src/composables/index.ts
  packages/ui/src/composables/useI18n.ts
  packages/ui/src/composables/useTranslation.ts
  packages/ui/src/main.ts
  packages/ui/src/services/global-config/global-config.ts
  packages/ui/src/services/global-config/types.ts
  packages/ui/src/services/i18n/defaults.ts
  packages/ui/src/services/i18n/index.ts
Labels: FEATURE, key feature

#2548 Fix/docs kitchensink bug fixes
  packages/docs/src/components/DocsNavigation.vue
  packages/docs/src/components/landing/LandingPreview.vue
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/getting-started/kitchensink/page-config.ts
  packages/docs/src/page-configs/ui-elements/alert/examples/Border.vue
  packages/docs/src/page-configs/ui-elements/app-bar/examples/Shadow.vue
  packages/docs/src/page-configs/ui-elements/list/examples/Clickable.vue
  packages/docs/src/page-configs/ui-elements/list/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/list/examples/Disabled.vue
  packages/docs/src/page-configs/ui-elements/list/examples/Fit.vue
  packages/docs/src/page-configs/ui-elements/list/examples/Lines.vue
  packages/docs/src/page-configs/ui-elements/spacer/examples/Default.vue
  packages/docs/src/page-configs/ui-elements/tabs/examples/Color.vue
  packages/docs/src/page-configs/ui-elements/tabs/examples/Content.vue
  packages/ui/src/components/va-breadcrumbs/VaBreadcrumbs.vue
  packages/ui/src/components/va-modal/VaModal.vue
  packages/ui/src/composables/useTranslation.ts
  packages/ui/src/services/i18n/defaults.ts
Labels: BUG

#2543 Fix/contribution guide bug
  packages/docs/src/components/DocsContent.vue
  packages/docs/src/components/DocsFileStructure.vue
  packages/docs/src/helpers/DocsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/types/configTypes.ts
  packages/ui/src/components/va-tree-view/index.ts
Labels: docs

#2562 feat: update docs for the icons setup
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/icons.ts
  packages/docs/src/page-configs/getting-started/configuration-guide/page-config.ts
Labels: docs

#2590 Fix/element color from css variable
  packages/docs/src/components/DocsAlert.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/composables/useElementBackground/TempMap.ts
  packages/ui/src/composables/useElementBackground/useDomChangesObserver.ts
  packages/ui/src/composables/useElementBackground/useElementBackground.ts
  packages/ui/src/composables/useElementBackground/useTempMap.ts
  packages/ui/src/composables/useElementBackground/utils.ts
Labels: BUG
