Repository epicmaxco/vuestic-ui, pull requests merged in 2022-04, with the labels that each got.

#1606 Add `useHover` hook in `VaSidebarItem`
  packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
Labels: component

#1622 [#1620] Fix `VaDateInput` icon color
  packages/ui/src/components/va-date-input/VaDateInput.vue
Labels: BUG, component

#1653 Fix warnings in demo examples
  packages/ui/src/components/va-backtop/VaBacktop.demo.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
  packages/ui/src/components/va-file-upload/VaFileUpload.vue
  packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
  packages/ui/src/components/va-modal/VaModal.vue
Labels: BUG, component

#1571 Fix the undefined error in slots
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/data-table/examples/CustomSlots.vue
  packages/docs/src/page-configs/ui-elements/data-table/page-config.ts
  packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
  packages/ui/src/components/va-data-table/VaDataTable.vue
  packages/ui/src/components/va-data-table/hooks/useFilterable.ts
  packages/ui/src/components/va-data-table/hooks/useRows.ts
  packages/ui/src/components/va-data-table/hooks/useSortable.ts
  packages/ui/src/components/va-data-table/types/index.ts
Labels: DISCUSSION, partially implemented, draft

#1650 [#1334] Remove junk css
  packages/ui/src/styles/global/_utility-global.scss
  packages/ui/src/styles/global/typography.scss
Labels: BUG

#1660 [#1654] Fix `VaOptionList`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/option-list/examples/Example.vue
  packages/docs/src/page-configs/ui-elements/option-list/examples/WithComplexData.vue
  packages/docs/src/page-configs/ui-elements/option-list/examples/WithSwitch.vue
  packages/ui/src/components/va-option-list/VaOptionList.demo.vue
  packages/ui/src/components/va-option-list/VaOptionList.vue
  packages/ui/src/components/va-pagination/VaPagination.vue
  packages/ui/src/composables/useSelectable.ts
  packages/ui/src/composables/useSelectableList.ts
  packages/ui/src/mixins/SelectableList/SelectableList.md
  packages/ui/src/mixins/SelectableList/SelectableListMixin.spec.disabled.ts
  packages/ui/src/mixins/SelectableList/SelectableListMixin.ts
  packages/ui/src/mixins/SelectableList/testIsSelectableList.ts
  packages/ui/src/services/utils.spec.ts
  packages/ui/src/services/utils.ts
Labels: BUG, component

#1687 [#1337] Add `anchor` slot to `VaModal`
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/ui-elements/modal/api-options.ts
  packages/docs/src/page-configs/ui-elements/modal/examples/Anchor.vue
  packages/docs/src/page-configs/ui-elements/modal/page-config.ts
  packages/ui/src/components/va-modal/VaModal.demo.vue
  packages/ui/src/components/va-modal/VaModal.vue
Labels: FEATURE, component

#1634 Remove withTransportConfig wrapper
  packages/ui/src/components/va-affix/VaAffix.vue
  packages/ui/src/components/va-config/VaConfig.demo.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/components/va-time-input/index.ts
  packages/ui/src/components/va-time-picker/VaTimePicker.vue
  packages/ui/src/components/va-time-picker/index.ts
  packages/ui/src/components/va-toast/index.ts
  packages/ui/src/services/component-config/component-config.ts
  packages/ui/src/services/config-transport/createProxyComponent.ts
  packages/ui/src/services/config-transport/withConfigTransport.spec.disabled.ts
  packages/ui/src/services/config-transport/withConfigTransport.ts
  packages/ui/src/utils/ssr-utils.ts
Labels: HIGH PRIORITY, review required

#1530 feat/optional services
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/main.ts
  packages/docs/src/page-configs/getting-started/installation/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/installation/code-examples/quick-start.ts
  packages/docs/src/page-configs/getting-started/installation/code-examples/tree-shaking.ts
  packages/docs/src/page-configs/getting-started/installation/page-config.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/code-examples/tree-shaking.ts
  packages/docs/src/page-configs/getting-started/tree-shaking/page-config.ts
  packages/docs/src/pages/getting-started/tree-shaking.vue
  packages/ui/src/components/va-dropdown/plugin/index.ts
  packages/ui/src/components/va-toast/plugin/index.ts
  packages/ui/src/main.ts
  packages/ui/src/services/color-config/plugin/create-color-config-plugin.ts
  packages/ui/src/services/color-config/plugin/index.ts
  packages/ui/src/services/global-config/plugin/index.ts
  packages/ui/src/vue-book/book-main.ts
  packages/ui/src/vuestic-plugin/create-vuestic/create-vuestic-essential.ts
  packages/ui/src/vuestic-plugin/create-vuestic/create-vuestic.ts
  packages/ui/src/vuestic-plugin/create-vuestic/index.ts
  packages/ui/src/vuestic-plugin/create-vuestic/nuxt/create-vuestic-nuxt-essential.ts
  packages/ui/src/vuestic-plugin/create-vuestic/nuxt/create-vuestic-nuxt.ts
  packages/ui/src/vuestic-plugin/create-vuestic/nuxt/index.ts
  packages/ui/src/vuestic-plugin/create-vuestic/nuxt/types.ts
  packages/ui/src/vuestic-plugin/index.ts
  packages/ui/src/vuestic-plugin/old/vuestic-plugin-without-components.ts
  packages/ui/src/vuestic-plugin/old/vuestic-plugin.ts
  packages/ui/src/vuestic-plugin/types/index.ts
  packages/ui/src/vuestic-plugin/utils/define-vuestic-plugin.ts
  packages/ui/src/vuestic-plugin/utils/global-properties.ts
  packages/ui/src/vuestic-plugin/utils/index.ts
  packages/ui/src/vuestic-plugin/utils/use-plugin.ts
  packages/ui/src/vuestic-plugin/vuestic-nuxt-plugin.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin-without-components.ts
  packages/ui/src/vuestic-plugin/vuestic-plugin.ts
Labels: FEATURE, refactoring

#1704 [#1703] Fix `VaNavbar` text colors
  packages/ui/src/components/va-navbar/VaNavbar.vue
  packages/ui/src/components/va-navbar/VaNavbarItem/VaNavbarItem.vue
  packages/ui/src/components/va-navbar/_variables.scss
Labels: BUG, component

#1708 [#1691] Fix `VaSlider` mobile behavior
  packages/docs/src/page-configs/ui-elements/slider/examples/Slots.vue
  packages/docs/src/page-configs/ui-elements/slider/examples/Vertical.vue
  packages/ui/src/components/va-slider/VaSlider.demo.vue
  packages/ui/src/components/va-slider/VaSlider.vue
  packages/ui/src/components/va-slider/_variables.scss
Labels: BUG, component

#1709 Added nuxt integration page.
  packages/docs/src/components/sidebar/navigationRoutes.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/getting-started/nuxt/code-examples/index.ts
  packages/docs/src/page-configs/getting-started/nuxt/page-config.ts
  packages/docs/src/pages/getting-started/nuxt.vue
Labels: review required

#1717 [#1705] Fix `VaDropdown` placement prop
  packages/docs/src/locales/en/en.json
  packages/docs/src/locales/ru/ru.json
  packages/docs/src/page-configs/services/components-config/examples/button.vue
  packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
  packages/nuxt-docs/locales/en.json
  packages/nuxt-docs/locales/ru.json
  packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
  packages/ui/src/components/va-date-input/VaDateInput.vue
  packages/ui/src/components/va-dropdown/VaDropdown.vue
  packages/ui/src/components/va-popover/VaPopover.vue
  packages/ui/src/components/va-select/VaSelect.demo.vue
  packages/ui/src/components/va-select/VaSelect.vue
  packages/ui/src/components/va-time-input/VaTimeInput.vue
  packages/ui/src/composables/usePopover.ts
Labels: BUG, component

#1580 feat: update translation docs approach
  packages/docs/src/helpers/DocsHelper.ts
  packages/docs/src/locales/en/en.json
  packages/docs/src/page-configs/contribution/documentation-page/page-config.ts
  packages/docs/src/page-configs/contribution/translation/page-config.ts
Labels: ON HOLD

#1612 [#735] pwa support added
  packages/docs/package.json
  packages/docs/public/manifest.json
  packages/docs/src/main.ts
  packages/docs/src/registerServiceWorker.ts
  yarn.lock
Labels: ON HOLD

#1611 [#1478] landing visual tweaks
  packages/docs/src/assets/fonts.scss
  packages/docs/src/components/header/Header.vue
  packages/docs/src/components/header/components/ColorDropdown.vue
  packages/docs/src/components/header/components/LanguageDropdown.vue
  packages/docs/src/components/header/components/VersionDropdown.vue
  packages/docs/src/components/landing/Admin.vue
  packages/docs/src/components/landing/Customize.vue
  packages/docs/src/components/landing/Footer.vue
  packages/docs/src/components/landing/Header.vue
  packages/docs/src/components/landing/OpenSource.vue
  packages/docs/src/components/landing/Preview.vue
  packages/docs/src/components/landing/SeamlessIntegration/SeamlessIntegration.vue
  packages/docs/src/config/theme-config.ts
Labels: ON HOLD
