Repository epicmaxco/vuestic-ui, pull requests merged in 2023-08, with the labels that each got.

#3654 docs: fix prop types
  packages/docs/modules/page-config/blocks/api/component-parser/index.ts
Labels: accessibility

#3632 fix(dropdown): more demos and fix multiple nodes rendered in proxy component
  packages/ui/src/components/va-dropdown/VaDropdownRender.demo.vue
  packages/ui/src/utils/headless.ts
Labels: BUG, component

#3657 fix: remove excluded props types from child components
  packages/ui/src/components/va-rating/VaRating.vue
  packages/ui/src/utils/component-options/extract-component-options.ts
  packages/ui/tsconfig.json
Labels: build

#3709 fix(#3680): data table hover in safari
  packages/ui/src/components/va-data-table/VaDataTable.vue
Labels: BUG

#3735 fix(va-input): proxy input event
  packages/ui/src/components/va-alert/VaAlert.vue
  packages/ui/src/components/va-input/VaInput.demo.vue
  packages/ui/src/components/va-input/VaInput.vue
  packages/ui/src/utils/combine-functions.ts
Labels: BUG

#3729 feat(theme-designer): init color preview
  packages/docs/page-config/styles/colors/components/Components.vue
  packages/docs/page-config/styles/colors/components/ThemeDesigner.vue
  packages/docs/page-config/styles/colors/components/theme-designer/ColorInput.vue
  packages/docs/page-config/styles/colors/index.ts
  packages/ui/src/components/va-color-input/VaColorInput.vue
  packages/ui/src/composables/useColors.ts
  packages/ui/src/services/current-app.ts
Labels: BUG, docs

#3739 fix(dropdown): prevent dropdown content from taking 100%
  packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
Labels: BUG

#3641 Added Linear stepper and custom step actions
  packages/docs/page-config/ui-elements/stepper/api-description.ts
  packages/docs/page-config/ui-elements/stepper/api-options.ts
  packages/docs/page-config/ui-elements/stepper/examples/CustomSave.vue
  packages/docs/page-config/ui-elements/stepper/examples/Linear.vue
  packages/docs/page-config/ui-elements/stepper/index.ts
  packages/ui/package.json
  packages/ui/src/components/va-stepper/VaStepper.demo.vue
  packages/ui/src/components/va-stepper/VaStepper.vue
  packages/ui/src/components/va-stepper/VaStepperStepButton.vue
  packages/ui/src/components/va-stepper/index.ts
  packages/ui/src/components/va-stepper/types.ts
  packages/ui/src/utils/un-function.ts
  packages/ui/src/utils/validators.ts
  yarn.lock
Labels: feature

#3748 fix(nuxt): use built-in `watch` option to restart nuxt
  packages/nuxt/package.json
  packages/nuxt/src/composables/use-config-file.ts
  packages/nuxt/src/module.ts
  yarn.lock
Labels: nuxt

#3718 feat(create-vuestic): tailwind option
  packages/create-vuestic/src/composables/useFiles.ts
  packages/create-vuestic/src/composables/usePackageJson.ts
  packages/create-vuestic/src/composables/useVuesticConfig/configDefault.ts
  packages/create-vuestic/src/composables/useVuesticConfig/configTreeShaking.ts
  packages/create-vuestic/src/generators/create-nuxt.ts
  packages/create-vuestic/src/generators/create-vue.ts
  packages/create-vuestic/src/index.ts
  packages/create-vuestic/src/prompts.ts
  packages/create-vuestic/src/steps/2.1.addAgGrid.ts
  packages/create-vuestic/src/steps/2.2.addTailwind.ts
  packages/create-vuestic/src/steps/2.addVuestic/insert-nuxt-module.ts
  packages/create-vuestic/src/steps/2.addVuestic/nuxt-app.ts
  packages/create-vuestic/src/steps/2.addVuestic/vue-app.ts
  packages/create-vuestic/src/steps/4.installDeps.ts
  packages/create-vuestic/src/utils/node-version.ts
  packages/create-vuestic/src/versions.ts
Labels: BUG, feature

#3738 feat(modal): before-ok and before-cancel methods
  packages/docs/page-config/ui-elements/modal/api-description.ts
  packages/ui/src/components/va-modal/VaModal.demo.vue
  packages/ui/src/components/va-modal/VaModal.vue
Labels: feature

#3776 docs Icon: fixed link to icon-config; docs Input: add hint to examle 'mask'
  packages/docs/page-config/ui-elements/icon/index.ts
  packages/docs/page-config/ui-elements/input/index.ts
Labels: docs
