Repository epicmaxco/vuestic-ui, pull requests merged in 2023-12, with the labels that each got.

#4035 Update useClickOutside.ts
  packages/ui/src/composables/useClickOutside.ts
Labels: BUG

#4039 Stories rework: VaChip
  packages/ui/src/components/va-chip/VaChip.demo.vue
  packages/ui/src/components/va-chip/VaChip.stories.ts
Labels: storybook

#4113 docs: minor miscellaneous improvements
  packages/docs/page-config/ui-elements/badge/examples/Placement.vue
  packages/docs/page-config/ui-elements/badge/examples/WithOtherComponents.vue
  packages/docs/page-config/ui-elements/button/examples/Tag.vue
  packages/docs/page-config/ui-elements/button/examples/WithIcon.vue
  packages/docs/page-config/ui-elements/carousel/examples/Ratio.vue
  packages/docs/page-config/ui-elements/carousel/examples/Slots.vue
Labels: docs
